-- Baseline: the schema as shipped in database/schema.sql.
--
-- No structural change here. schema.sql already creates every table with
-- CREATE TABLE IF NOT EXISTS, so a database built from it is already at this
-- version -- recording the baseline just gives the runner a known starting
-- point. Every change from here on gets its own numbered file.
--
-- DO, not SELECT: DO evaluates an expression and returns no result set, so
-- the runner has nothing to drain. A bare comment file would leave the batch
-- empty, which some drivers reject.
DO 1;
